### ISSUE TITLE
Questions about CLAHE N/D

### ISSUE THREAD

**Issue by Jemmagu** [jenicek/mdir#1]
Hi, I have two questions:

1. you mentioned that the best performing method is the VGG GeM combined with CLAHE N/D, so have you compared your retrieval performance with NetVlad? Which one is better?

2. Can you provide the test script then I can used to test the retrieval performance?

Really really hope to get your reply. Thanks in advance and have a nice day ! :)

**Comment by Jemmagu** [comment]
@jenicek

**Comment by jenicek** [comment]
Hi, the method has not been compared with NetVlad. You can evaluate the VGG GeM CLAHE N/D method using the `eval_clahe.yml` scenario in `mdir/examples/iccv19`.

Thank you for your interest, Tomas
